### ISSUE TITLE
Token Count

### ISSUE THREAD

**Issue by GarthVadar** [PhanaticGames/PKPvP#10]
In the killstreaks GUI, make it three rows (GUI SIZE) and in the bottom corner just like the kit selector one, put a sunflower in the corner and it shows with the LORE how many current tokens they have. Tokens reset on death btw :)

**Comment by mattparksjr** [comment]
Both of those are already there. Config

**Comment by mattparksjr** [comment]
This is avaliabvle for config at plugins/PKPvP/killstreaks.yml
