### ISSUE TITLE
Kill Streak Hotbar Icon

### ISSUE THREAD

**Issue by EspiosMC** [PhanaticGames/PKPvP#6]
In survival mode, if someone right clicks on the anvil, it opens up the GUI just fine, but players have the ability to place the anvil on the ground. Does not respawn. I also have OP, and I'm not sure if this contributes to the issue.

**Comment by mattparksjr** [comment]
This will be fixed. It was not due to being op, those players shoudn't be able to place anything anyways.

**Comment by mattparksjr** [comment]
This was fixed. Closeing.
